swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    #transport:        gmail
    #username:         "frederic.malard.pro@gmail.com"
    #password:         "Zar@2788"
    #host:             smtp.gmail.com
    #port:             25
    #encryption:       ssl
    #auth-mode:        login
    #spool: { type: 'memory' }
    #stream_options:
        #ssl:
            #allow_self_signed: true
            #verify_peer: false
            #verify_peer_name: false
