services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
    App\Twig\AppExtension:
        public: false
        tags: ["twig.extension"]

    # Uncomment any lines below to activate that Twig extension
    #Twig\Extensions\ArrayExtension: null
    #Twig\Extensions\DateExtension: null
    #Twig\Extensions\IntlExtension: null
    #Twig\Extensions\TextExtension: null
